version: '3.8'

services:
    # app:
    #     image: evgeniis73/trackingsystemapi:latest
    #     ports:
    #         - "7001:80"
    #     depends_on:
    #         - db
    #     environment:
    #         - DB_CONNECTION_STRING=Data Source=db;Initial Catalog=TrackingSystem;User Id=sa;Password=YourPassword123;Trust Server Certificate=true;
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "14330:1433" 
        environment:
            SA_PASSWORD: "YourPassword123"
            ACCEPT_EULA: "Y"
        volumes:
            - ./data:/var/opt/mssql/data
            - ./log:/var/opt/mssql/log
            - ./secrets:/var/opt/mssql/secrets