version: '3.8'

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "14330:1433" 
        environment:
            SA_PASSWORD: "YourPassword123"
            ACCEPT_EULA: "Y"
        volumes:
            - ./data:/var/opt/mssql/data
            - ./log:/var/opt/mssql/log
            - ./secrets:/var/opt/mssql/secrets